version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_vur_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql
    container_name: my_vur_bd
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - my-network

  vue:
    build:
      context: ./my-vue-app
      dockerfile: Dockerfile
    container_name: my_vur_frontend
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge



