version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_vur_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      HEX_KEY: ${HEX_KEY}
      VUR_USER: ${VUR_USER}
      VUR_PASS: ${VUR_PASS}
      VUR_DB: ${VUR_DB}
    networks:
       - backend
       - frontend

  db:
    image: mysql
    container_name: my_vur_bd
    environment:
      MYSQL_ROOT_PASSWORD: ${VUR_PASS}
      MYSQL_DATABASE: ${VUR_DB}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Прокидываем init.sql внутрь контейнера
    networks:
      - backend

  vue:
    build:
      context: ./my-vue-app
      dockerfile: Dockerfile
    container_name: my_vur_frontendзцв
    ports:
      - "8081:8081"
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge



